"""Emulation registry for Survival Kids games."""

from typing import Dict, Type

from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.survival_kids.parsers import (
    SurvivalKids2Parser,
    SurvivalKidsParser,
)
from gameboy_worlds.emulation.survival_kids.trackers import (
    SurvivalKidsAfterDrinkingWaterTracker,
    SurvivalKidsAfterFillingWaterTracker,
    SurvivalKidsAfternoonReferenceTracker,
    SurvivalKidsAnimalKilledTracker,
    SurvivalKidsBagIconTracker,
    SurvivalKidsBurnConfirmTracker,
    SurvivalKidsCanteenActionMenuTracker,
    SurvivalKidsCanteenChosenTracker,
    SurvivalKidsCanteenDrinkSelectedTracker,
    SurvivalKidsCanteenPickupDialogueTracker,
    SurvivalKidsCanteenTakeLeaveMenuTracker,
    SurvivalKidsCanteenUseSelectedTracker,
    SurvivalKidsChapter1PathClearedTracker,
    SurvivalKidsClubEquippedScreenTracker,
    SurvivalKidsCookedMeatActionMenuTracker,
    SurvivalKidsCookedMeatEatenDialogueTracker,
    SurvivalKidsCookedMeatEatSelectedTracker,
    SurvivalKidsCookedMeatStoredTracker,
    SurvivalKidsDayReferenceTracker,
    SurvivalKidsDrinkWaterTracker,
    SurvivalKidsEnteredShelterTracker,
    SurvivalKidsFeatherTakeLeaveMenuTracker,
    SurvivalKidsFireLitTracker,
    SurvivalKidsFoundRiverTracker,
    SurvivalKidsFruitActionMenuTracker,
    SurvivalKidsFruitEatenDialogueTracker,
    SurvivalKidsFruitEatenTracker,
    SurvivalKidsFruitEatSelectedTracker,
    SurvivalKidsFruitFoundDialogueTracker,
    SurvivalKidsFruitTakenDialogueTracker,
    SurvivalKidsGameViewportChangedTracker,
    SurvivalKidsGotTheBrdfeatherTracker,
    SurvivalKidsGotTheClamTracker,
    SurvivalKidsGotTheLogTracker,
    SurvivalKidsGotTheSharpStoneTracker,
    SurvivalKidsGotTheStickTracker,
    SurvivalKidsGotTheStoneTracker,
    SurvivalKidsGotTheTreeBarkTracker,
    SurvivalKidsGotTheVineTracker,
    SurvivalKidsGotTheWaterTracker,
    SurvivalKidsGrassCutBeforePickupLogTracker,
    SurvivalKidsGrassCutBeforePushStone2Tracker,
    SurvivalKidsGrassCutBeforeSharpStoneTracker,
    SurvivalKidsGrassCutTracker,
    SurvivalKidsHelmetFoundTracker,
    SurvivalKidsHpChangedTracker,
    SurvivalKidsHudTracker,
    SurvivalKidsHungerChangedTracker,
    SurvivalKidsInTheShelterTracker,
    SurvivalKidsInventoryAfterFireLitTracker,
    SurvivalKidsInventoryOpenTracker,
    SurvivalKidsInventoryOpenWithClubNearPryStoneTracker,
    SurvivalKidsInventoryOpenWithClubNearPushStone2Tracker,
    SurvivalKidsInventoryOpenWithClubTracker,
    SurvivalKidsInventorySelectItemTracker,
    SurvivalKidsKindlingMergedTracker,
    SurvivalKidsKnifeChosenTracker,
    SurvivalKidsKnifeEquippedScreenTracker,
    SurvivalKidsKnifeEquippedTracker,
    SurvivalKidsLogActionMenuTracker,
    SurvivalKidsLogFoundDialogueTracker,
    SurvivalKidsLogInventoryActionMenuTracker,
    SurvivalKidsLogInventorySelectTakeTracker,
    SurvivalKidsLogSelectTakeTracker,
    SurvivalKidsMergeConfirmTracker,
    SurvivalKidsMergeMenuTracker,
    SurvivalKidsMeatActionMenuTracker,
    SurvivalKidsMeatBurnSelectedTracker,
    SurvivalKidsMeatCookedDialogueTracker,
    SurvivalKidsMeatEatenDialogueTracker,
    SurvivalKidsMeatEatSelectedTracker,
    SurvivalKidsNearPryStoneTracker,
    SurvivalKidsNearPushStone2Tracker,
    SurvivalKidsNewPath1FoundTracker,
    SurvivalKidsNewPath2FoundTracker,
    SurvivalKidsNightReferenceTracker,
    SurvivalKidsObjectTracker,
    SurvivalKidsOCRTracker,
    SurvivalKidsPathAfterPriedStoneTracker,
    SurvivalKidsPathAfterPushedStone2Tracker,
    SurvivalKidsPathAfterBlockingGrassC1Tracker,
    SurvivalKidsPickupItemDialogueTracker,
    SurvivalKidsPathAfterBlockingGrassTracker,
    SurvivalKidsPryStoneDialogueTracker,
    SurvivalKidsPushStoneDialogue2Tracker,
    SurvivalKidsResolveHungerTracker,
    SurvivalKidsSelectClubNearPryStoneTracker,
    SurvivalKidsSelectClubTracker,
    SurvivalKidsSelectKindlingTracker,
    SurvivalKidsSelectDropTracker,
    SurvivalKidsSelectLogTracker,
    SurvivalKidsSelectMeatTracker,
    SurvivalKidsSelectTakeTracker,
    SurvivalKidsSharpStoneFoundTracker,
    SurvivalKidsStaminaChangedTracker,
    SurvivalKidsStatusBarChangedTracker,
    SurvivalKidsStonePushedOpen2Tracker,
    SurvivalKidsTakeLeaveMenuTracker,
    SurvivalKidsThirstChangedTracker,
    SurvivalKidsTreeBarkPickupDialogueTracker,
    SurvivalKidsUseKindlingTracker,
    SurvivalKidsVitalsTracker,
    SurvivalKidsWaterAvailableDialogueTracker,
    SurvivalKidsWaterMenuOpenTracker,
)


GAME_TO_GB_NAME: Dict[str, str] = {
    "survival_kids_1": "SurvivalKids.gbc",
    "survival_kids_2": "SurvivalKids2CN.gbc",
}

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "survival_kids_1": SurvivalKidsParser,
    "survival_kids_2": SurvivalKids2Parser,
}

AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "survival_kids_1": {
        "default": SurvivalKidsOCRTracker,
        "hud": SurvivalKidsHudTracker,
        "ocr": SurvivalKidsOCRTracker,
        "vitals": SurvivalKidsVitalsTracker,
        "status_bar_changed_test": SurvivalKidsStatusBarChangedTracker,
        "hp_changed_test": SurvivalKidsHpChangedTracker,
        "hunger_changed_test": SurvivalKidsHungerChangedTracker,
        "resolve_hunger_test": SurvivalKidsResolveHungerTracker,
        "thirst_changed_test": SurvivalKidsThirstChangedTracker,
        "drink_water_test": SurvivalKidsDrinkWaterTracker,
        "stamina_changed_test": SurvivalKidsStaminaChangedTracker,
        "game_viewport_changed_test": SurvivalKidsGameViewportChangedTracker,
        "grass_cut_test": SurvivalKidsGrassCutTracker,
        "inventory_open_test": SurvivalKidsInventoryOpenTracker,
        "inventory_after_fire_lit_test": SurvivalKidsInventoryAfterFireLitTracker,
        "inventory_select_item_test": SurvivalKidsInventorySelectItemTracker,
        "pickup_item_dialogue_test": SurvivalKidsPickupItemDialogueTracker,
        "canteen_pickup_dialogue_test": SurvivalKidsCanteenPickupDialogueTracker,
        "got_the_clam_test": SurvivalKidsGotTheClamTracker,
        "bag_icon_test": SurvivalKidsBagIconTracker,
        "object_test": SurvivalKidsObjectTracker,
        "knife_equipped_test": SurvivalKidsKnifeEquippedTracker,
        "knife_chosen_test": SurvivalKidsKnifeChosenTracker,
        "merge_menu_test": SurvivalKidsMergeMenuTracker,
        "merge_confirm_test": SurvivalKidsMergeConfirmTracker,
        "canteen_chosen_test": SurvivalKidsCanteenChosenTracker,
        "kindling_merged_test": SurvivalKidsKindlingMergedTracker,
        "take_leave_menu_test": SurvivalKidsTakeLeaveMenuTracker,
        "select_take_test": SurvivalKidsSelectTakeTracker,
        "select_drop_test": SurvivalKidsSelectDropTracker,
        "select_meat_test": SurvivalKidsSelectMeatTracker,
        "canteen_take_leave_menu_test": SurvivalKidsCanteenTakeLeaveMenuTracker,
        "canteen_action_menu_test": SurvivalKidsCanteenActionMenuTracker,
        "canteen_drink_selected_test": SurvivalKidsCanteenDrinkSelectedTracker,
        "canteen_use_selected_test": SurvivalKidsCanteenUseSelectedTracker,
        "animal_killed_test": SurvivalKidsAnimalKilledTracker,
        "chapter1_path_cleared_test": SurvivalKidsChapter1PathClearedTracker,
        "path_after_blocking_grass_test": SurvivalKidsPathAfterBlockingGrassTracker,
        "in_the_shelter_test": SurvivalKidsInTheShelterTracker,
        "new_path_1_found_test": SurvivalKidsNewPath1FoundTracker,
        "new_path_2_found_test": SurvivalKidsNewPath2FoundTracker,
        "sharp_stone_found_test": SurvivalKidsSharpStoneFoundTracker,
        "day_reference_test": SurvivalKidsDayReferenceTracker,
        "night_reference_test": SurvivalKidsNightReferenceTracker,
        "entered_shelter_test": SurvivalKidsEnteredShelterTracker,
        "found_river_test": SurvivalKidsFoundRiverTracker,
        "water_menu_open_test": SurvivalKidsWaterMenuOpenTracker,
        "after_filling_water_test": SurvivalKidsAfterFillingWaterTracker,
        "after_drinking_water_test": SurvivalKidsAfterDrinkingWaterTracker,
        "got_the_water_test": SurvivalKidsGotTheWaterTracker,
        "got_the_stick_test": SurvivalKidsGotTheStickTracker,
        "got_the_tree_bark_test": SurvivalKidsGotTheTreeBarkTracker,
        "got_the_sharp_stone_test": SurvivalKidsGotTheSharpStoneTracker,
        "got_the_stone_test": SurvivalKidsGotTheStoneTracker,
        "got_the_vine_test": SurvivalKidsGotTheVineTracker,
        "got_the_brdfeather_test": SurvivalKidsGotTheBrdfeatherTracker,
        "select_kindling_test": SurvivalKidsSelectKindlingTracker,
        "fire_lit_test": SurvivalKidsFireLitTracker,
        "use_kindling_test": SurvivalKidsUseKindlingTracker,
        "feather_take_leave_menu_test": SurvivalKidsFeatherTakeLeaveMenuTracker,
        "meat_action_menu_test": SurvivalKidsMeatActionMenuTracker,
        "cooked_meat_action_menu_test": SurvivalKidsCookedMeatActionMenuTracker,
        "cooked_meat_eat_selected_test": SurvivalKidsCookedMeatEatSelectedTracker,
        "meat_burn_selected_test": SurvivalKidsMeatBurnSelectedTracker,
        "burn_confirm_test": SurvivalKidsBurnConfirmTracker,
        "meat_eat_selected_test": SurvivalKidsMeatEatSelectedTracker,
        "meat_eaten_dialogue_test": SurvivalKidsMeatEatenDialogueTracker,
        "meat_cooked_dialogue_test": SurvivalKidsMeatCookedDialogueTracker,
        "cooked_meat_eaten_dialogue_test": SurvivalKidsCookedMeatEatenDialogueTracker,
        "cooked_meat_stored_test": SurvivalKidsCookedMeatStoredTracker,
    },
    "survival_kids_2": {
        "default": SurvivalKidsOCRTracker,
        "hud": SurvivalKidsHudTracker,
        "ocr": SurvivalKidsOCRTracker,
        "vitals": SurvivalKidsVitalsTracker,
        "status_bar_changed_test": SurvivalKidsStatusBarChangedTracker,
        "hp_changed_test": SurvivalKidsHpChangedTracker,
        "hunger_changed_test": SurvivalKidsHungerChangedTracker,
        "resolve_hunger_test": SurvivalKidsResolveHungerTracker,
        "thirst_changed_test": SurvivalKidsThirstChangedTracker,
        "drink_water_test": SurvivalKidsDrinkWaterTracker,
        "stamina_changed_test": SurvivalKidsStaminaChangedTracker,
        "game_viewport_changed_test": SurvivalKidsGameViewportChangedTracker,
        "grass_cut_test": SurvivalKidsGrassCutTracker,
        "water_available_dialogue_test": SurvivalKidsWaterAvailableDialogueTracker,
        "grass_cut_before_sharp_stone_test": SurvivalKidsGrassCutBeforeSharpStoneTracker,
        "grass_cut_before_pickup_log_test": SurvivalKidsGrassCutBeforePickupLogTracker,
        "grass_cut_before_push_stone_2_test": SurvivalKidsGrassCutBeforePushStone2Tracker,
        "chapter1_path_cleared_test": SurvivalKidsChapter1PathClearedTracker,
        "path_after_blocking_grass_test": SurvivalKidsPathAfterBlockingGrassTracker,
        "path_after_blocking_grass_c1_test": SurvivalKidsPathAfterBlockingGrassC1Tracker,
        "new_path_1_found_test": SurvivalKidsNewPath1FoundTracker,
        "new_path_2_found_test": SurvivalKidsNewPath2FoundTracker,
        "sharp_stone_found_test": SurvivalKidsSharpStoneFoundTracker,
        "inventory_open_test": SurvivalKidsInventoryOpenTracker,
        "inventory_open_with_club_test": SurvivalKidsInventoryOpenWithClubTracker,
        "inventory_open_with_club_near_pry_stone_test": SurvivalKidsInventoryOpenWithClubNearPryStoneTracker,
        "inventory_open_with_club_near_push_stone_2_test": SurvivalKidsInventoryOpenWithClubNearPushStone2Tracker,
        "inventory_select_item_test": SurvivalKidsInventorySelectItemTracker,
        "object_test": SurvivalKidsObjectTracker,
        "helmet_found_test": SurvivalKidsHelmetFoundTracker,
        "knife_chosen_test": SurvivalKidsKnifeChosenTracker,
        "knife_equipped_test": SurvivalKidsKnifeEquippedScreenTracker,
        "knife_equipped_prompt_test": SurvivalKidsKnifeEquippedScreenTracker,
        "club_equipped_test": SurvivalKidsClubEquippedScreenTracker,
        "select_club_test": SurvivalKidsSelectClubTracker,
        "select_club_near_pry_stone_test": SurvivalKidsSelectClubNearPryStoneTracker,
        "near_pry_stone_test": SurvivalKidsNearPryStoneTracker,
        "near_push_stone_2_test": SurvivalKidsNearPushStone2Tracker,
        "pry_stone_dialogue_test": SurvivalKidsPryStoneDialogueTracker,
        "push_stone_dialogue_2_test": SurvivalKidsPushStoneDialogue2Tracker,
        "path_after_pried_stone_test": SurvivalKidsPathAfterPriedStoneTracker,
        "stone_pushed_open_2_test": SurvivalKidsStonePushedOpen2Tracker,
        "path_after_pushed_stone_2_test": SurvivalKidsPathAfterPushedStone2Tracker,
        "log_found_dialogue_test": SurvivalKidsLogFoundDialogueTracker,
        "log_action_menu_test": SurvivalKidsLogActionMenuTracker,
        "log_select_take_test": SurvivalKidsLogSelectTakeTracker,
        "select_log_test": SurvivalKidsSelectLogTracker,
        "log_inventory_action_menu_test": SurvivalKidsLogInventoryActionMenuTracker,
        "log_inventory_select_take_test": SurvivalKidsLogInventorySelectTakeTracker,
        "got_the_log_test": SurvivalKidsGotTheLogTracker,
        "fruit_found_dialogue_test": SurvivalKidsFruitFoundDialogueTracker,
        "fruit_action_menu_test": SurvivalKidsFruitActionMenuTracker,
        "fruit_eat_selected_test": SurvivalKidsFruitEatSelectedTracker,
        "fruit_taken_dialogue_test": SurvivalKidsFruitTakenDialogueTracker,
        "fruit_eaten_dialogue_test": SurvivalKidsFruitEatenDialogueTracker,
        "fruit_eaten_test": SurvivalKidsFruitEatenTracker,
        "got_the_stick_test": SurvivalKidsGotTheStickTracker,
        "tree_bark_pickup_dialogue_test": SurvivalKidsTreeBarkPickupDialogueTracker,
        "got_the_tree_bark_test": SurvivalKidsGotTheTreeBarkTracker,
        "got_the_sharp_stone_test": SurvivalKidsGotTheSharpStoneTracker,
        "got_the_stone_test": SurvivalKidsGotTheStoneTracker,
        "got_the_vine_test": SurvivalKidsGotTheVineTracker,
        "afternoon_reference_test": SurvivalKidsAfternoonReferenceTracker,
        "day_reference_test": SurvivalKidsDayReferenceTracker,
        "night_reference_test": SurvivalKidsNightReferenceTracker,
        "entered_shelter_test": SurvivalKidsEnteredShelterTracker,
        "found_river_test": SurvivalKidsFoundRiverTracker,
    },
}

AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "survival_kids_1": {
        "default": Emulator,
    },
    "survival_kids_2": {
        "default": Emulator,
    },
}
